swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      produces:
      - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transactions/account/{accountID}:
    get:
      tags:
        - Transactions Modules
      security:
        - Bearer: []
      summary: Get User transactions
      description: Retrieve all transactions for the current month grouped by account
      produces:
      - application/json
      responses:
        "200":
          description: User transactions retrieved successfully
          schema:
            $ref: "#/definitions/UserTransactions"
        "500":
          description: Internal Server Error
  /user/transactions/{transactionId}:
    get:
      tags:
        - Transactions Modules
      security:
        - Bearer: []
      summary: Get Transaction details
      description: Retrieve details of a specific transaction
      parameters:
        - in: path
          name: transactionId
          required: true
          description: ID of the transaction to retrieve details for transactionId
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: transaction details retrieved successfully
          schema:
            $ref: "#/definitions/TransactionDetails"
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    patch:
      tags:
        - Transactions Modules
      security:
        - Bearer: []
      summary: Update Transaction Details
      description: Update information about a transaction
      parameters:
        - in: body
          name: body
          description: ID of the transaction to update
          required: true
          schema:
           $ref: "#/definitions/TransactionUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: User account updated successfully
          schema:
            $ref:  "#/definitions/TransactionUpdateResponse"
        "409":
          description: Invalid Fields
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  UserTransactions:
    type: array
    properties:
      status:
        type: integer
      body:
        type: object
        properties:
          date: 
            type: string
          description:
            type: string
          amount:
            type: number
          balance: 
            type: number
  TransactionDetails:
    type: object
    properties:
      status:
        type: integer
      transactionId:
        type: string
        description: Id transaction
      amount:
        type: number
        description: transaction amount
      date:
        type: string
        format: date-time
        description: transaction date-time
      description:
        type: string
      accountId:
        type: string
        description: Id of the account associated with the transaction
      balance:
        type: number
        description: trnasaction balance
      transactionType:
        type: string
      note: 
        type: string
      category:
        type: string
  TransactionUpdate:
    type: object
    properties:
      description:
        type: string
        description: new transaction description
      transactionType:
        type: string
        description: new transaction type
      note:
        type: string
        description: new transaction note
      category: 
        type: string
        description: new transaction category
  TransactionUpdateResponse:
    type: object
    properties: 
      status:
        type: integer
      transactionId:
        type: string
      amount:
        type: number
      date: 
        type: string
        format: date-time
      description:
        type: string
      accountId:
        type: string
      balance:
        type: number
      transactionType:
        type: string
      note: 
        type: string
      category:
        type: string
      

